### ISSUE TITLE
The keys DurangoKeyExtractor found are useless?

### ISSUE THREAD

**Issue by ch1dyc4t** [emoose/xvdtool#38]
Extract keys from xsapi.dll by DurangoKeyExtractor:
```
XVDTool-0.53.0.0-win-x64> .\DurangoKeyExtractor.exe .\xsapi.dll
DurangoKeyExtractor 0.53.0-5737d20: Durango key extractor
Scanning .\xsapi.dll for known keys...
Found XvdSigningKey "GreenGamesPublicKey" at offset 0x239B0
Found XvdSigningKey "GreenXvdPublicKey" at offset 0x23BD0
Found Odk "RedOdk" at offset 0x23DF0
Found XvdSigningKey "RedXvdPrivateKey" at offset 0x23E10
Found 4 keys :)
Saving keys to "C:\Users\xxxxxxxxxx\AppData\Local\Temp\.net\DurangoKeyExtractor\j3pmypap.1rq\extracted"...
```

Check keys by XVDTool:
```
XVDTool-0.53.0.0-win-x64> .\XVDTool.exe -lk
XVDTool 0.53.0-5737d20: XVD file manipulator

No desired signkey provided, falling back to RedXvdPrivateKey
No desired CIK provided, falling back to 33ec8436-5a0e-4f0d-b1ce-3f29c3955039
No desired or invalid ODK provided, will try to use ODK indicated by XVD header
Warning: Signkey could not be loaded, you will be unable to resign XVD headers!
Warning: CIK could not be loaded!

Known Durango keys:
XvdSigningKey:
    RedXvdPrivateKey: Loaded: False Hash: 8E2B60377006D87EE850334C42FC200081386A838C65D96D1EA52032AA9628C5 Size: 2331
    GreenXvdPublicKey: Loaded: False Hash: 618C5FB1193040AF8BC1C0199B850B4B5C42E43CE388129180284E4EF0B18082 Size: 539
    GreenGamesPublicKey: Loaded: False Hash: 183F0AE05431E4AD91554E88946967C872997227DBE6C85116F5FD2FD2D1229E Size: 539
Odk:
    RedOdk: Loaded: False Hash: CA37132DFB4B811506AE4DC45F45970FED8FE5E58C1BACB259F1B96145B0EBC6 Size: 32
Cik:
    33ec8436-5a0e-4f0d-b1ce-3f29c3955039: Loaded: False Hash: 6786C11B788ED5CCE3C7695425CB82970347180650893D1B5613B2EFB33F9F4E Size: 32
    f0522b7c-7fc1-d806-43e3-68a5daab06da: Loaded: False Hash: B767CE5F83224375E663A1E01044EA05E8022C033D96BED952475D87F0566642 Size: 32
```

Decrypt by XVDTool err:
```
\XVDTool-0.53.0.0-win-x64> .\XVDTool.exe -nd -eu '..\$SystemUpdate\updater.xvd'
XVDTool 0.53.0-5737d20: XVD file manipulator

No desired signkey provided, falling back to RedXvdPrivateKey
No desired CIK provided, falling back to 33ec8436-5a0e-4f0d-b1ce-3f29c3955039
No desired or invalid ODK provided, will try to use ODK indicated by XVD header
Warning: Signkey could not be loaded, you will be unable to resign XVD headers!
Warning: CIK could not be loaded!

Loading file from ..\$SystemUpdate\updater.xvd...

Decrypting XVD using "<ODK indicated by XVD header>" key...
Unhandled exception. System.InvalidOperationException: ODK with Id 'RedOdk' is known but not loaded! Cannot crypt CIK in header
   at LibXboxOne.XvdFile.CryptHeaderCik(Boolean encrypt)
   at LibXboxOne.XvdFile.Decrypt()
   at XVDTool.Program.<>c__DisplayClass4_0.<Main>g__PerformActions|1(XvdFile file)
   at XVDTool.Program.Main(String[] args)
```

Show info: 
```
\XVDTool-0.53.0.0-win-x64> .\XVDTool.exe -nd -i '..\$SystemUpdate\updater.xvd'
XVDTool 0.53.0-5737d20: XVD file manipulator

No desired signkey provided, falling back to RedXvdPrivateKey
No desired CIK provided, falling back to 33ec8436-5a0e-4f0d-b1ce-3f29c3955039
No desired or invalid ODK provided, will try to use ODK indicated by XVD header
Warning: Signkey could not be loaded, you will be unable to resign XVD headers!
Warning: CIK could not be loaded!

Loading file from ..\$SystemUpdate\updater.xvd...

XvdMiscInfo:
... ...

Cannot get XvdFilesystem from encrypted package
```

What is the right way to decrypt XVDs? Thanks.

**Comment by tuxuser** [comment]
https://github.com/emoose/xvdtool#possible-locations-to-store-keys

**Comment by ch1dyc4t** [comment]
excuse me. i thought XVDTool  would load keys extracted by DurangoKeyExtractor automatically.
