### ISSUE TITLE
how to open the xbox game bin file please tell me

### ISSUE THREAD

**Issue by gitusercxpc** [emoose/xvdtool#63]
when i decrypt and mount it it woldn t let me open it ived been trying and i got close to doing it but bc im dumb and only lil brain i couldnt do the rest it kept saying invalid bin file when i put it in poweriso and other bin readers i did make it a nuget and it only had the dependencys folder and that was my final brain cell idea and im only 13 u can call me STUPID becouse i am

**Comment by gitusercxpc** [comment]
or am i doing it the wrong way

**Comment by rileyhack** [comment]
it says this if its a xvd .\xvdtool -m -mp "E:" 1234.exvd.xvd
XVDTool 1.0.0: XVD file manipulator

Unhandled exception. System.Exception: Misaligned CIK, expecting array of 0x30 bytes: 0x10 bytes: GUID, 0x20 bytes: Key
   at LibXboxOne.Keys.DurangoKeys.LoadCikKeys(Byte[] keyData, Guid[]& loadedKeys) in C:\Users\Riley\xvdtool\LibXboxOne\Keys\DurangoKeys.cs:line 111
   at LibXboxOne.Keys.DurangoKeys.LoadKey(KeyType keyType, String keyFilePath) in C:\Users\Riley\xvdtool\LibXboxOne\Keys\DurangoKeys.cs:line 234
   at LibXboxOne.Keys.DurangoKeys.LoadKeysRecursive(String basePath) in C:\Users\Riley\xvdtool\LibXboxOne\Keys\DurangoKeys.cs:line 259
   at XVDTool.Program.Main(String[] args) in C:\Users\Riley\xvdtool\XVDTool\Program.cs:line 206
PS C:\xvdtool\XVDTool\bin\Release\net7.0>

**Comment by rileyhack** [comment]
and when its the decrypted bin file its still .\xvdtool -m -mp "E:" 1234.exvd.bin
XVDTool 1.0.0: XVD file manipulator

Unhandled exception. System.Exception: Misaligned CIK, expecting array of 0x30 bytes: 0x10 bytes: GUID, 0x20 bytes: Key
   at LibXboxOne.Keys.DurangoKeys.LoadCikKeys(Byte[] keyData, Guid[]& loadedKeys) in C:\Users\Riley\xvdtool\LibXboxOne\Keys\DurangoKeys.cs:line 111
   at LibXboxOne.Keys.DurangoKeys.LoadKey(KeyType keyType, String keyFilePath) in C:\Users\Riley\xvdtool\LibXboxOne\Keys\DurangoKeys.cs:line 234
   at LibXboxOne.Keys.DurangoKeys.LoadKeysRecursive(String basePath) in C:\Users\Riley\xvdtool\LibXboxOne\Keys\DurangoKeys.cs:line 259
   at XVDTool.Program.Main(String[] args) in C:\Users\Riley\xvdtool\XVDTool\Program.cs:line 206
